(3/2)^2
install.packages("readxl")
install.packages("readxl")
install.packages("readxl")
library(readxl)
импор�_ <- read_excel("G:/универ/5 курс/импорт.xlsx")
View(импор�_)
library(readxl)
import_battery <- read_excel("G:/универ/5 курс/батаре�\271ки/import_battery.xlsx")
View(import_battery)
library(readxl)
View(import_battery)
plot(import_battery)
View(import_battery)
ts(import_battery)
tsImport < - ts(import_battery [,2],start = 2017,frequency = 12)
tsImport <-ts(import_battery [,2], start = 2017, frequency = 12)
plot(tsImport)
install.packages("imputeTS")
library("imputeTS", lib.loc="C:/LIB")
tsImportPoln <- na_mean(tsImport, option = 'mean', maxgap = Inf)
View(tsImportPoln)
plot(tsImportPoln)
tsImportPoln2 <- na_seasplit(tsImport, algorithm = 'interpolation', find_frequency = FALSE, maxgap = Inf)
plot(tsImportPoln2)
library("forecast", lib.loc="C:/LIB")
fit < - stl(tsImportPoln2, s.window = "periodic")
plot(tsImportPoln2)
ts1 <- ts(as.vector(tsImportPoln2))
fit <- stl(ts1, s.window = "periodic")
stlData <- stl(ts1,t.window = 13, s.window = 12)
plot(tsImportPoln2)
